---
 C3PO_REPO: "https://github.com/omec-project/c3po.git"
 NGIC_REPO: "https://github.com/omec-project/ngic-rtc.git"
 MME_REPO: "https://github.com/omec-project/openmme.git"
 FREEDIAMETER_REPO: "https://github.com/omec-project/freediameter.git"
# ODL_REPO: ""
 TR_REPO: "https://github.com/wanare-2017/deployment.git"
 SGX_REPO: "https://github.com/omec-project/c3po.git"

 C3PO_REPO_DIR: "/opt/c3po"
 MME_REPO_DIR: "/opt/openmme"
 FREEDIAMETER_DIR: "{{ MME_REPO_DIR }}/modules/freediameter"
 NGIC_REPO_DIR: "/opt/ngic-rtc"
 ODL_REPO_DIR: "/opt/netty_odl_fpc"
 TR_REPO_DIR: "/opt/deployment"

 MME_COMMIT_ID: "cbefb0950b324e21a0922cc1c654a186c68cd5ba"
 NGIC_COMMIT_ID: "7200ac1d515ea775c0896aa432e29ff7bd0ff5fa"
 C3PO_COMMIT_ID: "82539248739bd069959b15ad37e9bc4f09c67f86"
 ODL_COMMIT_ID: "d6608df8dbc5c2d840d74590fc4750acca715429"
 SGX_COMMIT_ID: "82539248739bd069959b15ad37e9bc4f09c67f86"
